### ISSUE TITLE
Does not compile with stock firmware 1.94.0-beta

### ISSUE THREAD

**Issue by Zorkeel** [jdlien/Kaleidoscope-LEDEffect-FunctionalColor#11]
Hello, I experience some problems compiling this plugin. Starting with stock firmware, including this plugin and compiling throws this error : 

`Arduino: 1.8.9 (Mac OS X), Board: "Keyboardio Model 01"

In file included from /var/folders/33/p2xpwvxs4lbflr7g9hkszvqc0000gn/T/arduino_modified_sketch_537675/Model01-Firmware.ino:408:0:
/Users/zorkeel/Documents/Arduino/libraries/Kaleidoscope-LEDEffect-FunctionalColor-master/src/Kaleidoscope-LEDEffect-FunctionalColor.h:608:18: error: 'KeyAddr' has not been declared
   void refreshAt(KeyAddr key_addr) final;
                  ^
/Users/zorkeel/Documents/Arduino/libraries/Kaleidoscope-LEDEffect-FunctionalColor-master/src/Kaleidoscope-LEDEffect-FunctionalColor.h:608:8: error: 'void kaleidoscope::plugin::LEDFunctionalColor::FunctionalColor::refreshAt(int)' marked 'final', but is not virtual
   void refreshAt(KeyAddr key_addr) final;
        ^
Multiple libraries were found for "HID.h"
 Used: /Users/zorkeel/Library/Arduino15/packages/keyboardio/hardware/avr/1.94.0-beta/libraries/HID
 Not used: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/HID
exit status 1
Error compiling for board Keyboardio Model 01.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

Any insights ?

Thanks a lot, Zorkeel

**Comment by jdlien** [comment]
This is the very latest Keyboardio firmware? If so, I wonder if there has been a regression and if an older version might work better. These sorts of issues are supposed to be fixed now.

I also had been using macOS, but apparently these issues never happened on other platforms.

**Comment by Zorkeel** [comment]
Yes, from the Arduino IDE, Boards Manager screen, after updating keyboardio, the versions I can choose are :
  1.94.0-beta
  1.93.0-beta
  1.92.0-beta
  1.91.0-beta
  1.90.0-beta
  1.23.0
  1.22.0
  1.19.0

I'll try to use an older version. It's not obvious to me where the problem is, this is the first plugin I try to use on my keyboardio, I hope I'm not missing something :)

If the error occur only on macOS, I'll try to install arduino on my PC and flash my keyboard from here.

I'll let you know how it turns out, thanks!

**Comment by Zorkeel** [comment]
I have the same error on Windows:

`WARNING: Category 'Debug' in library Kaleidoscope-Hardware-Virtual is not valid. Setting to 'Uncategorized'
In file included from C:\Users\Zorkeel\AppData\Local\Temp\arduino_modified_sketch_66153\Model01-Firmware.ino:73:0:

C:\Users\Zorkeel\Documents\Arduino\libraries\Kaleidoscope-LEDEffect-FunctionalColor-master\src/Kaleidoscope-LEDEffect-FunctionalColor.h:608:18: error: 'KeyAddr' has not been declared

   void refreshAt(KeyAddr key_addr) final;

                  ^

C:\Users\Zorkeel\Documents\Arduino\libraries\Kaleidoscope-LEDEffect-FunctionalColor-master\src/Kaleidoscope-LEDEffect-FunctionalColor.h:608:8: error: 'void kaleidoscope::plugin::LEDFunctionalColor::FunctionalColor::refreshAt(int)' marked 'final', but is not virtual

   void refreshAt(KeyAddr key_addr) final;

        ^

Multiple libraries were found for "HID.h"
 Used: C:\Users\Zorkeel\AppData\Local\Arduino15\packages\keyboardio\hardware\avr\1.94.0-beta\libraries\HID
 Not used: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\HID
exit status 1
Error compiling for board Keyboardio Model 01.`

Here are the steps I've followed:
- Install Arduino from arduino-1.8.9-windows.exe
- in Arduino, open File>Preferences and fill in the 'Additional Boards Managers URLs' input with https://raw.githubusercontent.com/keyboardio/boardsmanager/master/package_keyboardio_index.json
- Tools>Boards>Boards Manager, search for keyboardio and install 1.94.0-beta version
- Tools>Boards> select Keyboardio Model 01
- Tools>Port> select COM3 (Keyboardio Model 01)
- File>Examples> select Model01-Firmware
- from your repo download the .zip file
- Sketch>Include Library>Add .ZIP Library
- Add the lines from your 'Basic Use of FunctionalColor' example
- Click the Verify button

Thanks for your help, Zorkeel

**Comment by Zorkeel** [comment]
Hi @jdlien 

The new firmware (1.96) solves the problem, it works like a charm!

Thank you, Zorkeel
